# application config
app:
  name: sqlrest
  port: 8000
  debug: true
  open_auth: true
  token_secret: akhcJgYMneNRNEAIR5zymBz83DHjIj3
  log_path: ./logs

database:
  # 数据库类型
  type: sqlite
  # type: mysql
  host: localhost
  port: 3306
  user: root
  password:
  db: database


admin:
  open: true
  user: admin
  password: RHp6SnVxh5JBckA3
  